//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevUtils.Elas.Tasks.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevUtils.Elas.Tasks.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsd:schema xmlns:xlf=&quot;urn:oasis:names:tc:xliff:document:1.2&quot; 
        ///		   attributeFormDefault=&quot;unqualified&quot; 
        ///		   elementFormDefault=&quot;qualified&quot; 
        ///		   targetNamespace=&quot;urn:devutils:names:tc:xliff:document:1.2&quot; 
        ///		   xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;xsd:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot; /&gt;
        ///	&lt;xsd:import namespace=&quot;urn:oasis:names:tc:xliff:document:1.2&quot; /&gt;
        ///
        ///	&lt;xsd:attribute name=&quot;absent&quot;&gt;
        ///	&lt;/xsd:attribute&gt;
        ///&lt;/xsd:schema&gt;.
        /// </summary>
        internal static string elas_xliff_extension_1_2_transitional {
            get {
                return ResourceManager.GetString("elas_xliff_extension_1_2_transitional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;!--
        ///
        ///May-19-2004:
        ///- Changed the &lt;choice&gt; for ElemType_header, moving minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot; from its elements 
        ///to &lt;choice&gt; itself.
        ///- Added &lt;choice&gt; for ElemType_trans-unit to allow &quot;any order&quot; for &lt;context-group&gt;, &lt;count-group&gt;, &lt;prop-group&gt;, &lt;note&gt;, and
        ///&lt;alt-trans&gt;.
        ///
        ///Oct-2005
        ///- updated version info to 1.2
        ///- equiv-trans attribute to &lt;trans-unit&gt; element 
        ///- merged-trans attribute for &lt;group&gt; element
        ///- Add the &lt;seg-source&gt; element as optional [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xliff_core_1_2_transitional {
            get {
                return ResourceManager.GetString("xliff_core_1_2_transitional", resourceCulture);
            }
        }
    }
}
